### PR TITLE
Add upload-to-pypi Makefile targets

### PR DESCRIPTION
**Pull request by jameshiew**
Ran `make upload-to-pypi` to publish the v0.8.7 release - https://pypi.org/project/mws/0.8.7/

Then manually drafted the Github release - tag `v0.8.7`, title `0.8.7`.

This release was signed, can be verified like so

```shell script
wget https://files.pythonhosted.org/packages/38/96/9773b3827b277dc8c9e4b33ad51110ebcf6d8653c652816d44ad0b55838b/mws-0.8.7.tar.gz
wget https://files.pythonhosted.org/packages/38/96/9773b3827b277dc8c9e4b33ad51110ebcf6d8653c652816d44ad0b55838b/mws-0.8.7.tar.gz.asc
gpg --verify mws-0.8.7.tar.gz.asc mws-0.8.7.tar.gz
```

### CODE REVIEW

**Comment by GriceTurrble** [comment]
@jameshiew Is this relevant for a "hotfix" style merge to `master`, then? And will this same change be reflected in `develop` moving forward?

(This is not my purview, just asking for purposes of branch management)

**Comment by Bobspadger** [comment]
This is a great thing to have in the Makefile, however, I would possibly argue that having the entire build sequence in the `.PHONY` section could be dangerous - quite often Makefiles print out the options as help by default, not actually run and create.

Example from one of mine for building via Ansible:

```
help:
        @echo 'Makefile for building our Automation Server                                           '
        @echo '                                                                                      '
        @echo 'Usage:                                                                                '
        @echo '   make deploy                         Create the server with Ansible                 '
        @echo '   make deploy-verbose                 Create the server with verbose output          '
        @echo '   make check-syntax                   Check the Syntax of the Playbooks              '
        @echo '   make test                           Run the playbooks in test mode                 '
        @echo '   make test-step                      Run the playbooks in test mode and step through'
        @echo '                                                                                       '

.PHONY: help

```
all the destructive commands have to be explicitly run.

shall I refactor this?

**Comment by jameshiew** [comment]
> This is a great thing to have in the Makefile, however, I would possibly argue that having the entire build sequence in the `.PHONY` section could be dangerous - quite often Makefiles print out the options as help by default, not actually run and create.
> 
> Example from one of mine for building via Ansible:
> 
> ```
> help:
>         @echo 'Makefile for building our Automation Server                                           '
>         @echo '                                                                                      '
>         @echo 'Usage:                                                                                '
>         @echo '   make deploy                         Create the server with Ansible                 '
>         @echo '   make deploy-verbose                 Create the server with verbose output          '
>         @echo '   make check-syntax                   Check the Syntax of the Playbooks              '
>         @echo '   make test                           Run the playbooks in test mode                 '
>         @echo '   make test-step                      Run the playbooks in test mode and step through'
>         @echo '                                                                                       '
> 
> .PHONY: help
> ```
> 
> all the destructive commands have to be explicitly run.
> 
> shall I refactor this?

Sounds good, feel free to take over this branch and do as you see best!

> @jameshiew Is this relevant for a "hotfix" style merge to `master`, then? And will this same change be reflected in `develop` moving forward?
> 
> (This is not my purview, just asking for purposes of branch management)

Yep, the next step after this merges would be to sync `master` back up into `develop` again i.e. get the Makefile etc into the `develop` branch as well (I don't think there should need to be any differences between them but there might be)

**Comment by Bobspadger** [comment]
I've checked out this PR (using the CLI options above) and have made changes to the Makefile to add in some safeguards and confirmations.

However, my github knowledge is not great (Gitlab for the win!) and I'm stuck with this on my computer, with James repo as the master.

To save me messing this up - whats the best course of action from here? @GriceTurrble

**Comment by Bobspadger** [comment]
@GriceTurrble I'm going to suggest that maybe this is no longer required if we are going to make the method of releasing a new version to pypi to be via Github actions?

**Comment by GriceTurrble** [comment]
Probably not, we can do it all in the workflows.

I'll work on that during my break week coming up. :)

**Pull request closed without merging**
