### PR TITLE
Fix a pair of docstrings in `offamazonpayments`

### PR DESCRIPTION
**Pull request by xmo-odoo**
* `capture` is missing two parameters, copy from `refund` which has them
* add linebreak between docstring text and info fields in `capture` and `refund`, tooling generally doesn't deal well otherwise
* remove todo comment: though incomplete the docstrings in the file match sphinx's docstring style

### CODE REVIEW

**Review by GriceTurrble — CHANGES_REQUESTED** [review]
Thank you for the addition. :)

Minor tweak: while we're here, could you please add in some short descriptions for these parameters? Even just copying part of the descriptions from [Amazon's docs](https://amazonpaylegacyintegrationguide.s3.amazonaws.com/docs/amazon-pay-api/capture.html) would be sufficient.

You can also drop a link to those specific docs that relate to each of these operations, and that would fulfill the other TODO (line 7).

**Comment by xmo-odoo** [comment]
Updated the docstrings to try and document most everything. There are a few sticking points though:

* the same parameter names are used for client-side references and amazon-generated identifiers, which I fear may be confusing to users? (I'm not actually a user of the API) e.g. the `auth_id` of `authorize` and `get_authortization_status` or `capture` are completely different things
* the API exposes `get_billing_agreement_details` which is part of the *automatic payments* APIs, but no other API of that set seems exposed, is it actually useful?
* I added `currency` to `authorize` as it's part of the Amazon API and the other functions expose it, figured it might come in handy
* I did not document `get_order_reference_details` (and the rest of the order details stuff) either because the call here doesn't match [the documented API](https://amazonpaylegacyintegrationguide.s3.amazonaws.com/docs/amazon-pay-api/getorderreferencedetails.html) so it seemed odd: there is no `AddressConsentToken` in the API (neither is there one in `get_billing_agreement_details`), though both have an `AccessToken`. Is `AddressConsentToken` the older name for `AccessToken` and both can be used still?

**Comment by GriceTurrble** [comment]
> * the same parameter names are used for client-side references and amazon-generated identifiers, which I fear may be confusing to users? (I'm not actually a user of the API) e.g. the `auth_id` of `authorize` and `get_authortization_status` or `capture` are completely different things

I think it's fine to re-use `auth_id` in those contexts. Amazon makes them more verbose arguments like `AmazonAuthorizationId` and `AuthorizationReferenceId`, but that distinction is more important to Amazon than to us. If we can at least document what the argument maps to, it should be fine.

> * the API exposes `get_billing_agreement_details` which is part of the _automatic payments_ APIs, but no other API of that set seems exposed, is it actually useful?

I'm not a user of the API myself, but I figure this module is intended to cover the whole Amazon Pay legacy API for MWS. Likely the author of our first merge of this API only needed these particular methods.

We have missing methods in other APIs, as well, so not really that big of a deal.

> * I added `currency` to `authorize` as it's part of the Amazon API and the other functions expose it, figured it might come in handy

👍 Thanks!

> * I did not document `get_order_reference_details` (and the rest of the order details stuff) either because the call here doesn't match [the documented API](https://amazonpaylegacyintegrationguide.s3.amazonaws.com/docs/amazon-pay-api/getorderreferencedetails.html) so it seemed odd: there is no `AddressConsentToken` in the API (neither is there one in `get_billing_agreement_details`), though both have an `AccessToken`. Is `AddressConsentToken` the older name for `AccessToken` and both can be used still?

Possibly, and good catch! I'd appreciate an update for those so they're more complete.

**Comment by xmo-odoo** [comment]
@GriceTurrble updated the `get_order_reference_details` and `get_billing_agreement_details` to take an `access_token` and set it as `AccessToken`.

**Review by GriceTurrble — APPROVED** [review]

**Pull request merged**
