### PR TITLE
_UPLOAD_VAT_INVOICE_

### PR DESCRIPTION
**Pull request by masavini**
added _UPLOAD_VAT_INVOICE_ support

### CODE REVIEW

**Comment by Bobspadger** [comment]
Thanks for the PR @masavini 

Could you please re-submit against develop ?

**Comment by masavini** [comment]
> Thanks for the PR @masavini
> 
> Could you please re-submit against develop ?

just done...

**Comment by GriceTurrble** [comment]
See #166 for comments.

@Bobspadger Should we continue attempting to merge this for a 0.x release? It's a minor change overall, but I imagine the impact for sellers in EU and GB regions is significant.

**Comment by Bobspadger** [comment]
I think its probably worth it. I'd like to try and give it a test but struggling with time at the moment, not sure if anyone else is able to ?

**Pull request merged**
