### PR TITLE
add all current marketplaces and alphabetize by country code

### PR DESCRIPTION
**Pull request by agritheory**
Several more marketplaces have been added since I looked at this last:
https://docs.developer.amazonservices.com/en_US/dev_guide/DG_Endpoints.html

### CODE REVIEW

**Comment by agritheory** [comment]
> Similar comment as on #154 , but it seems this is also missing the `AE` region. Can you double check, please?

Yes, copy paste mistake with the AE marketplace, good catch.

**Comment by agritheory** [comment]
@GriceTurrble Is there a test for this and if not, what would be a reasonable thing to add?

**Comment by GriceTurrble** [comment]
> @GriceTurrble Is there a test for this and if not, what would be a reasonable thing to add?

There is a small test case in `test_mws.py` that asserts the CA region:

https://github.com/python-amazon-mws/python-amazon-mws/blob/8004de585aa4aa1c6a032202b4609d90ad7ee803/tests/request_methods/test_mws.py#L15-L25

The latter of these two tests is a bit trivial (testing that a hard-coded value remains hard-coded correctly), but the former makes sense: ensuring that the domain is returned correctly for a chosen marketplace, which dictates how the request URI is built.

If you want to do a bit of busywork to extend that and cover all the domains, that would be appreciated. Otherwise I'll just accept this as-is later today. :)

**Comment by agritheory** [comment]
> If you want to do a bit of busywork to extend that and cover all the domains, that would be appreciated.

I think it makes sense to explicitly assert that UK and GB are the same and agree that the rest is busywork. I would prefer to add the tests before you merge and keep the fire lit!

**Comment by agritheory** [comment]
@GriceTurrble Galen, please review the tests I added when you get a chance.

**Pull request merged**
