### PR TITLE
Fix bug: Remove trailing comma

### PR DESCRIPTION
**Pull request by ronbeltran**

### CODE REVIEW

**Comment by ronbeltran** [comment]
A trailing comma converts a list to a tuple, when `requires.append('enum34')` is called throws an error.
>>> a = [],
>>> type(a)
<type 'tuple'>
>>> a.append(True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'tuple' object has no attribute 'append'

**Comment by Bobspadger** [comment]
looks sensible to me.

**Comment by elcolumbio** [comment]
On which python version and which setuptools version are you?
It should be fixed if you are using the develop branch.

If not we can fix your issue here. But it's good that the manual adding is very slightly protected.

In official examples they use our **­`[],`** syntax more often (in some examples they also use lists).

**Comment by elcolumbio** [comment]
I am quite sure you should never alter the setup.py file from outside.
Because the dependencies get installed when you type pip install mws, so you have to reinstall it and rechange it every time?

Potential underlying problems with enum34 are very complicated, because you can use every combination of python version and setuptools version.

Our solution in the development branch is quite good it seems we use a mix of this:
https://hynek.me/articles/conditional-python-dependencies/

**Comment by ronbeltran** [comment]
@elcolumbio Our Python and setuptools were old versions and during pip install of mws it breaks.

```
Python 2.7.3 (default, Oct 26 2016, 21:01:49) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import setuptools
>>> setuptools.__version__
'0.6c11
```

`pip install -e git+https://github.com/python-amazon-mws/python-amazon-mws.git@develop#egg=mws`

So in our case, with the old python and setuptools versions, this line is executed:
https://github.com/python-amazon-mws/python-amazon-mws/blob/develop/setup.py#L25
and raised AttributeError: 'tuple' object has no attribute 'append'.

**Comment by elcolumbio** [comment]
Ok i feel for you having to use such an old environment. I hope they pay you good and let you upgrade soon.

Indeed now i see the bug.
I would change the requires.append('enum34') to something like requires = (requires[0] + ['enum34'], ). You like it and is that working?
But i am a strong advocat to remove python 2.7 support on 1.1.2020 anyway.

**Comment by elcolumbio** [comment]
Also we could update the comment instead older versions to versions older than version 18. Also remove flake8 reference this code doesn't exist anymore.

**Comment by elcolumbio** [comment]
```python3 
requires = [
    'requests',
]
# Compatible for setup versions older than 18.
if sys.version_info < (3, 4):
    requires.append('enum34')
 ```

Remove the rest, because in our case the logic is not needed?

**Pull request merged**
