### PR TITLE
Feature implement get my fees estimate

### PR DESCRIPTION
**Pull request by mdaif**
This PR aims to implement `get_my_fees_estimate`

The tricky part about this method is to:
1. Reuse the existing utils in a DRY manner.
2. Enforcing the method's client to structure the input data into a certain (pretty complicated) format.

Following some best practices from Domain Driven Design, I used classes to represent the value objects (such as ListingPrice, ShippingPrice, .. etc). This allows the client to construct the complicated request in a simple manner.
I also made use of Python3 type annotations to clarify the data types.

I've also included a test case to elaborate how to use the method.

### CODE REVIEW

**Comment by GriceTurrble** [comment]
@mdaif Thank you for the contribution. Please note that a major update has been posted to `develop` branch (in the works for some time now), so you may want to sync up there first before we come back for a review.

Among the changes:

- The `utils.py` module was removed, in favor of a `utils` directory with different modules tied to specific concerns. If you have utilities to add, you will want to find the right home for them.
  - I don't see your previous changes to utilities in the changed files currently, so not sure if that got removed or if you changed it already.
- Request method signatures are changing slightly. See examples in newer code, where `action` positional arg is required instead of an `'Action'` key in the `data` dict.

Other than that, the changes look good so far. I'll come back for a more thorough review once you've had time to check the upstream changes. Give me a poke when ready. :)

**Comment by mdaif** [comment]
@GriceTurrble Thanks a lot for your timely review and comments ! :))
I've addressed your comments and extended the test case.
There's however a missing style check but I don't know what's failing exactly, I ran flake8 on my modules and it's passing.

**Comment by GriceTurrble** [comment]
The failing check uses Black for code formatting. Simply `pip install black` in your virtual env and then `black .` on the root directory of the repo, and the code will be reformatted automatically.

Occasionally this can introduce new linting errors, so please double-check `flake8` output after formatting.

**Comment by mdaif** [comment]
Hi @GriceTurrble 
Thanks for the tip, will do that. A quick note though, it seems like the support for Python 3.5 is still required although black is a 3.6+ package and Python 3.5 reached the end of its life on September 13th, 2020. Will support for Python 3.5 be dropped soon ? (I know about the new SP API that'll deprecate MWS anyhow, but that'll probably take quite some time)

**Comment by GriceTurrble** [comment]
As a matter of fact, I dropped 3.5 from the test suite on dev just prior to the update this week. So no, 3.5 support is not required. :)

**Comment by mdaif** [comment]
Great :'D ... I've also just noticed that ubuntu-latest,3.5 check is not there anymore, but it's still in `.travis.yml` file, so to be on the safe side my code still supported that.

**Comment by mdaif** [comment]
I've tried to include dataclasses but the different python versions made that difficult. Anyhow, I think we're ready for the second round of reviews :))

**Comment by GriceTurrble** [comment]
Ah. I'm ignoring the travis settings myself, so no big. If it covers 3.5 support, all the better, but we just won't be running tests against it.

**Comment by mdaif** [comment]
I merged too early, there were a couple of failing checks. I'll have a look at that.

**Comment by mdaif** [comment]
Fixed now.

**Review by GriceTurrble — APPROVED** [review]
A nice joint effort at the end there. Thank you for incorporating my suggested changes.

This adds in the `get_my_fees_estimate`, as the PR states, but also introduces a good framework for us to add datatype models that are closer in structure to the ones used by MWS, allowing us to offload some data validation and serialization concerns to those models. Adds a bit of complication, of course, but sets a great baseline and provides those tools to other developers to hopefully make their lives a little easier.

I hope to build off what this change adds as we add coverage for the remainder of MWS in the near future. Thank you kindly!

**Comment by mdaif** [comment]
That was awesome ! Thank you ! :))

**Pull request merged**
