### PR TITLE
fix clean_params

### PR DESCRIPTION
**Pull request by elcolumbio**
clean_params should not delete boolean False values. Now removes only those values which are None.

since we introduced the apis subfolder we have to declare it in the setup.py so we can pip install mws.

### CODE REVIEW

**Comment by elcolumbio** [comment]
i am going to sleep. The if clause is still bad. If someone enters an integer 0 as value it gets removed.
Maybe add more cases or remove empty stuff in the end.

**Comment by elcolumbio** [comment]
or dont remove anything?

**Comment by elcolumbio** [comment]
agreed is not None is better.
Only for empty strings not, but do we want to remove them?

**Comment by elcolumbio** [comment]
i thought it would be easy, but we have to fix some more stuff.
which i think is good anyway:
in reports in line211 for example
report_types = report_types or []

but that is anyway bad, i can just remove those lines

**Comment by GriceTurrble** [comment]
Yes, empty strings should be removed, as well. So `v is not None and v != ""`. Everything else should remain.

**Comment by elcolumbio** [comment]
since empty list are not getting removed and will throw an error in clean_params.
but there shouldnt be any lists in the first place?

**Comment by elcolumbio** [comment]
i think its fine. don't have to make it more complicated.

**Comment by elcolumbio** [comment]
this seems to be 2 helpful bug fixes. Can we merge it?

**Comment by Lacrymology** [comment]
bump this. I was about to push a PR for the same fix

**Comment by altendky** [comment]
`and` is not a good thing in a PR title.  Might be worth making a separate PR for just the little packages thing since the discussion here seems to be about the other piece.

**Comment by Bobspadger** [comment]
> `and` is not a good thing in a PR title. Might be worth making a separate PR for just the little packages thing since the discussion here seems to be about the other piece.

I agree, I think this should be two PR's, one for fixing setup, one for clean_params

@elcolumbio are you able to do this ?

**Pull request merged**
